### ISSUE TITLE
genteert.dll missing after uninstall

### ISSUE THREAD

**Issue by jimorc** [copperspice/doxypress#23] opened 2019-01-26 16:29 UTC
I am updating a web post that I wrote on integrating DoxyPress with Visual Studio. Since I originally wrote that post, I have reinstalled Windows 10. All Windows updates that are available as of this morning are installed.

I downloaded the DoxyPress Windows x64 installer and ran it. DoxyPress installed properly. In order to capture screenshots of the installation process, I uninstalled DoxyPress, then ran the installer again. Now when the installer starts, it displays two message boxes. The first contains:

> ...\AppData\Local\Temp\genteert.dll is either not designed to run on Windows or it contains an error. Try installing the program again using the original installation media or contact your system administrator or the software vendor for support. Error status 0xc0000020

and the second contains:

> Cannot load ...\AppData\Local\Temp\genteert.dll

I have downloaded the installer again and run it. Same result. I tried the 32-bit installer. Again, same result.

Searching the error status from the first message box, I am led to a Microsoft page on fixing Windows Update errors. Following the instructions on that page does not solve the problem. I guess that would be logical since genteert.dll is user specific and not a Windows DLL.

It appears that the DoxyPress uninstaller uninstalls genteert.dll.

**Comment by agserm** [comment] 2019-01-28 05:09
Thank you for your report. We use a product called CreateInstall to generate the windows install executable, and we do not have this configured to delete any system DLLs.

As far as I am aware, the installer and uninstaller do not rely on any third party libraries which means they should contain everything needed to install on supported versions of windows.  We will contact the developer of CreateInstall to find out if this is a known issue and what the resolution might be.

**Comment by agserm** [comment] 2019-10-15 02:57
Closing this ticket as we have been unable to reproduce this issue in testing.

**Closed by agserm** 2019-10-15 02:57 UTC
